name: VanaByte
version: '${project.version}'
main: me.cade.vanabyte.VanaByte
api-version: 1.19
depend: [PlayerParticles]

commands:
  spawn:
  changeworld:
  hidescoreboard:
  unhidescoreboard:
  fly:
  heal:
  vanascuteness:

