name: VanaByte
version: '${project.version}'
main: me.cade.vanabyte.VanaByte
api-version: '1.20'

commands:
  spawn:
  changeworld:
  hidescoreboard:
  unhidescoreboard:
  fly:
  heal:
  vanascuteness:
